# Generated by Django 5.0.3 on 2024-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_arrangements',
            name='match_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='player_1_result',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='player_2_result',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='player_3_result',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='player_4_result',
            field=models.FloatField(default=0),
        ),
    ]
