# Generated by Django 5.0.3 on 2024-09-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_match_arrangements_match_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_arrangements',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='match_results',
            name='player_4_result',
        ),
    ]
